"""empty message

Revision ID: 57d3d8834b20
Revises: 
Create Date: 2019-07-03 13:05:58.561022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d3d8834b20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('custID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('suburb', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('custID')
    )
    op.create_table('driver',
    sa.Column('driverID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('vehicle', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('driverID')
    )
    op.create_table('item',
    sa.Column('itemID', sa.Integer(), nullable=False),
    sa.Column('decsription', sa.String(length=128), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('itemID')
    )
    op.create_table('order',
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('custID', sa.Integer(), nullable=True),
    sa.Column('driverID', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custID'], ['customer.custID'], ),
    sa.ForeignKeyConstraint(['driverID'], ['driver.driverID'], ),
    sa.PrimaryKeyConstraint('orderID')
    )
    op.create_table('quantity',
    sa.Column('itemID', sa.Integer(), nullable=False),
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itemID'], ['item.itemID'], ),
    sa.ForeignKeyConstraint(['orderID'], ['order.orderID'], ),
    sa.PrimaryKeyConstraint('itemID', 'orderID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quantity')
    op.drop_table('order')
    op.drop_table('item')
    op.drop_table('driver')
    op.drop_table('customer')
    # ### end Alembic commands ###
